language: node_js
cache:
    directories:
        - ~/.npm
notifications:
    email: false
node_js:
    - '10'
    - '11'
    - '12'
script:
    - npm run test && npm run build

jobs:
    include:
        - stage: coverage
          script: npm run report-coverage
